spring:
  application:
    name: busi-xml-client
server:
  port: 8004
  servlet:
    context-path: / # 项目contextPath
    tomcat:
      uri-encoding: UTF-8 # tomcat的URI编码
      max-threads: 800 # tomcat最大线程数，默认为200
      min-spare-threads: 30 # Tomcat启动初始化的线程数，默认值25