### 集群容错测试
GET {{url}}/clusterFault
Accept: application/json

### 负载均衡-随机
GET {{url}}/loadBalance/random
Accept: application/json

### 负载均衡-轮询
GET {{url}}/loadBalance/roundRobin
Accept: application/json

### 负载均衡-最少活跃调用数
GET {{url}}/loadBalance/leastActive
Accept: application/json

### 负载均衡-一致性Hash
GET {{url}}/loadBalance/consistentHash
Accept: application/json

### 直连提供者
GET {{url}}/directConnect
Accept: application/json

### 多协议
GET {{url}}/multiProtocol
Accept: application/json

### 服务分组
GET {{url}}/group
Accept: application/json

### 服务分组-字符串结果合并
GET {{url}}/group/mergerString
Accept: application/json

### 多版本
GET {{url}}/multiVersion
Accept: application/json

### 参数校验
POST {{url}}/validation/save
Content-Type: application/json

{
  "name": "MooN",
  "email": "moon@moon.com",
  "age": 28
}

### 泛化调用
GET {{url}}/generic/order/getDetail?id=11
Accept: application/json

### 泛化调用-方法参数为pojo
POST {{url}}/generic/user/regist
Content-Type: application/json

{
  "name": "MooN",
  "address": "天锁斩月",
  "balance": 132
}

### 泛化调用-自定义泛化接口实现
GET {{url}}/generic/customGeneric?param=123
Accept: application/json

### 上下文信息-隐式参数传递
GET {{url}}/context/attachment
Accept: application/json

###
